# Generated by Django 4.0 on 2021-12-09 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.TextField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='meeting_rooms.location')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_time', models.TextField()),
                ('reason', models.TextField()),
                ('attendee', models.IntegerField(blank=True)),
                ('guest', models.IntegerField(blank=True)),
                ('tea', models.IntegerField(blank=True)),
                ('water', models.IntegerField(blank=True)),
                ('coffee', models.IntegerField(blank=True)),
                ('water_dispenser', models.BooleanField(blank=True)),
                ('meal_courtyard', models.IntegerField(blank=True)),
                ('meal_buffet', models.IntegerField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_rooms.meetingroom')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.user')),
            ],
        ),
    ]
