# Generated by Django 4.0 on 2022-01-04 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.TextField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='meeting_rooms.location')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField(blank=True, default='')),
                ('use_date', models.DateField()),
                ('start_time', models.TextField()),
                ('end_time', models.TextField()),
                ('reason', models.TextField()),
                ('attendee', models.IntegerField(default=0)),
                ('guest', models.IntegerField(default=0)),
                ('tea', models.IntegerField(default=0)),
                ('water', models.IntegerField(default=0)),
                ('coffee', models.IntegerField(default=0)),
                ('water_dispenser', models.BooleanField(default=False)),
                ('meal_courtyard', models.IntegerField(default=0)),
                ('meal_buffet', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting_rooms.meetingroom')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='RoomExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTING', 'Requesting'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject')], default='REQUESTING', max_length=20)),
                ('reason', models.TextField()),
                ('reply', models.TextField(blank=True)),
                ('read', models.BooleanField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('replier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_requests', to='auth.user')),
                ('requester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='auth.user')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='meeting_rooms.reservation')),
            ],
        ),
    ]
