# Generated by Django 4.0 on 2022-01-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
