# Generated by Django 4.0 on 2021-12-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms', '0002_reservation_use_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='attendee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='coffee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='meal_buffet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='meal_courtyard',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tea',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='water',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='water_dispenser',
            field=models.BooleanField(default=False),
        ),
    ]
