# Generated by Django 4.0 on 2021-12-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_rooms', '0003_alter_reservation_attendee_alter_reservation_coffee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='host',
            field=models.TextField(default=''),
        ),
    ]
